### ISSUE TITLE
Checking for changed order in JSON with NSOrderedSet

### ISSUE THREAD

**Issue by dersvenhesse** [SyncDB/Sync#233]
Hi there,
I'm not sure whether this is a bug or if this might be solvable through configuration.

As far as I know arrays in JSON are ordered and CoreData allows ordering as well using `NSOrderedSet`. So in my opinion Sync should change the data when the order of an array has changed, which does not happen at the moment.

I [forked SyncAppNetDemo](https://github.com/dersvenhesse/SyncAppNetDemo) and built a many-to-many relationship with humans and cars to illustrate the issue. Start the app and let Sync do its job. Then change the order of the cars in `global.json` and start the app again. Now I think the ordering in CoreData should be updated and the `changeNotification` for updated objects triggered.

How do you guys think this should be handled?

**Comment by 3lvis** [comment]
Hi @dersvenhesse,

You're right, this isn't handled correctly. The piece of code that should include this functionality is [here](https://github.com/hyperoslo/Sync/blob/d6e521ceb1bea7cecd1530ce0191744afdb0916f/Source/NSManagedObject%2BSync.swift#L168-L172).

Right now it just checks if the relationship has being added, before it adds it, it doesn't check if the position has changed. It does this to avoid triggering KVO notifications if changes haven't been made.

To be able to implement this feature, I think we would need to know the previous index of the evaluated relationship, if it has changed we could use any of the fancy NSMutableOrderedSet methods to move elements.

Do you have any suggestions on how we could do that?

Also, why using sorted relationship instead of sorting by `X` using a NSSortDescriptor?

**Comment by dersvenhesse** [comment]
Since the data structure itself does support ordering, I don't see why an extra attribute should be used to order. ;) 
Furthermore, the ordering might be an attribute on the relation rather than an object. For example, when using images, the same image might be on first place in one object, but on third in an other.

I do think as well it will be necessary to compare indexes and then use something like `moveObjectsAtIndexes ` or `exchangeObjectAtIndex`. But, tbh, I don't have an exact implementation in mind yet.

**Comment by 3lvis** [comment]
Maybe pulling the entire list of changes, looping through it and verifying if the index is the same. Could be a good option. If the index is not the same, figure out the new index and change it's position on the set

**Comment by 3lvis** [comment]
💥  -> https://github.com/SyncDB/Sync/issues/327
